# Generated by Django 5.0.1 on 2024-01-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=5)),
                ('action', models.CharField(max_length=10)),
                ('at', models.FloatField()),
                ('pair', models.CharField(max_length=5)),
            ],
        ),
    ]
